spring.application.name=seat-reservation-service

spring.datasource.url=jdbc:postgresql://localhost:5432/seat_reservation_db
spring.datasource.username=seat_reservation_user
spring.datasource.password=seat_reservation_dev

spring.flyway.enabled=true

spring.jpa.hibernate.ddl-auto=validate